name: auto_trigger_test

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'com/quotes/**'

env:
  GIT_COMMIT_SHA: ${{github.sha}}
  GIT_EVENT_REF: ${{github.event.ref}}
  GIT_COMMIT_MSG: ${{github.event.head_commit.message}}

jobs:
  ci-dev:
    name: "CI - Dev - Identifying Changes"
    runs-on: ubuntu-latest
    steps:
      - name: "Identifying Git Event Details."
        run: |
          echo "Latest Commit happened - $GIT_EVENT_REF "
          echo "Latest Commit sha - $GIT_COMMIT_SHA "
          echo "Latest Commit message - $GIT_COMMIT_MSG"
          echo "Github Workspace - $GITHUB_WORKSPACE "
      
      - name: "Checkout DEV branch."
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Identifying list of updated files/folders."
        run: | 
          git show --stat $GIT_COMMIT_SHA
  
  cd-uat:
    name: "CD - UAT Deployment"
    if: starstartsWith(github.event.head_commit.message, 'Deploy -')
    environment: approval_env
    runs-on: ubuntu-latest
    needs: ci-dev
    
    steps:
    - name: "Checkout UAT branch."
      uses: actions/checkout@v4
      with:
        ref: uat
        fetch-depth: 0

    - name: "Deploying Changes from DEV branch to UAT branch."
      run: |
        git config --global user.email "krishboss11@gmail.com"
        git config --global user.name "krishnansanu"
        
        echo "Cherry-picking from Dev branch."
        git cherry-pick -X theirs $GIT_COMMIT_SHA

        echo "Checking Status"
        git status

        echo "pushing the changes to UAT"
        git push

        echo "Completed commit!!!"
