name: auto_trigger_test

on:
  push:
    branches:
      - 'main'
    paths:
      - 'com/quotes/**'

env:
  GIT_COMMIT_SHA: $GITHUB_SHA
  GIT_EVENT_REF: ${{github.event.ref}}

jobs:
  identify_changes:
    name: identify_changes
    runs-on: ubuntu-latest
    steps:
      - name: "Extracting information from the latest commit"
        run: |
          echo "Latest Commit happened - ${{ env:GIT_EVENT_REF }}"
          echo "Latest Commit sha - ${{ env:GIT_COMMIT_SHA }}"
