name: auto_trigger_test

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'com/quotes/**'

env:
  GIT_COMMIT_SHA: ${{github.sha}}
  GIT_EVENT_REF: ${{github.event.ref}}

jobs:
  identify_changes:
    name: identify_changes
    runs-on: ubuntu-latest
    steps:
      - name: "Extracting information from the latest commit"
        run: |
          echo "Latest Commit happened - $GIT_EVENT_REF "
          echo "Latest Commit sha - $GIT_COMMIT_SHA "
          echo "Github Workspace - $GITHUB_WORKSPACE "
      
      - name: checkout dev branch
        uses: actions/checkout@v4

      - name: Modified Files details
        run: | 
          git show --stat $GIT_COMMIT_SHA
