name: list_files_from_commit_sha

on:
  workflow_dispatch

env:
  GIT_COMMIT_SHA_DEV: '7a0290919bc1d883d8c788162ecd32e53c15c3d3'
  

jobs:
  ci-dev:
    name: "CI - Dev - Identifying Changes"
    runs-on: ubuntu-latest
    steps:
      - name: "Identifying Git Event Details."
        run: |
          echo "Latest Commit happened - $GIT_EVENT_REF "
      
      - name: "Checkout DEV branch."
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Identifying list of updated files/folders."
        run: | 
          echo "Checking stats based on dev sha"
          git show --stat $GIT_COMMIT_SHA_DEV
          echo "---------------------------------"
          echo "Checking stats based on uat sha"
          git show --stat --name-only $GIT_COMMIT_SHA_DEV
          echo "---------------------------------"
          
