name: list_files_from_commit_sha

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        required: true
        type: string

jobs:
  display_details:
    name: display_details
    runs-on: ubuntu-latest

    steps:
      - name: print_commit_sha
        run: |
          echo "Commit Sha Input - ${{ github.event.inputs.commit_sha }}"
          
      - name: check_out
        uses: actions/checkout@v4
        
      

      - name: display_details_based_on_commit_sha
        env:
          SRC_FOLDER_PATH: 'com/src/'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          echo "files ---> $files "
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout ${{ github.event.inputs.commit_sha }} -- $files # copy files from the source branch
