name: auto_trigger_test

on:
  workflow_dispatch

env:
  GIT_COMMIT_SHA_DEV: 'f42d66fb41268ad77521ec92c23f219bb0cc7a55'
  GIT_COMMIT_SHA_UAT: '718d1b199dc4922f904db59ba87161b78e586b9d'
  

jobs:
  ci-dev:
    name: "CI - Dev - Identifying Changes"
    runs-on: ubuntu-latest
    steps:
      - name: "Identifying Git Event Details."
        run: |
          echo "Latest Commit happened - $GIT_EVENT_REF "
      
      - name: "Checkout DEV branch."
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Identifying list of updated files/folders."
        run: | 
          echo "Checking stats based on dev sha"
          git show --stat $GIT_COMMIT_SHA_DEV
          echo ""
          echo "Checking stats based on uat sha"
          git show --stat $GIT_COMMIT_SHA_UAT
