name: test_workflow_trigger

on:
  workflow_dispatch

env:
  action_type: 'CI - '
  action_env: 'default'

jobs:
  ci-build:
    name: ci-build
    env: 
      action_type: 'CI - '
      action_env: 'dev'
      
    runs-on: ubuntu-latest

    outputs:
      action_color: ${{ steps.dev-build.outputs.action_color }}
    steps:
      - name: create-build
        id: dev-build
        run: |
          echo $action_type $action_env
          echo my_var="DEV_VALUE" >> $GITHUB_ENV
          echo action_color="Yellow" >> $GITHUB_OUTPUT

      - name: test-print-variable
        run: |
          echo "Printing my_var - ${{ env.my_var }}"
          echo "Action Color - ${{ jobs.ci-build.outputs.action_color }}"

  cd-test:
    name: cd-test
    environment: 'test'
    needs: ci-build
    env:
      action_type: 'CD - '
      action_env: 'test'
    
    runs-on: ubuntu-latest
    steps:
      - name: create-build
        run: |
          echo $action_type $action_env
          echo "Printing my_var - ${{ env.my_var }}"
          echo "Action Color - ${{ steps.dev-build.outputs.action_color }}"
    
  cd-uat:
    name: cd-uat
    environment: 'test'
    needs: cd-test
    env:
      action_type: 'CD - '
      action_env: 'uat'
    
    runs-on: ubuntu-latest
    steps:
      - name: create-build
        run: |
          echo $action_type $action_env
  
  cd-prod:
    name: cd-prod
    environment: 'test'
    needs: cd-uat
    env:
      action_type: 'CD - '
      action_env: 'prod'
    
    runs-on: ubuntu-latest
    steps:
      - name: create-build
        run: |
          echo $action_type $action_env
