name: test_python

on:
  workflow_dispatch

env:
  IICS_USER_NAME: ${{ secrets.IICS_USER_NAME }}

jobs:
  informatica_processing:
    name: "Informatica Processing"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout DEV branch"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: "Install Python"
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: "Install python Modules"
        run: | 
          python -m pip install --upgrade pip
          pip install requests
      
      - name: "IICS login"
        run: | 
          echo "IICS-USER-NAME: $IICS_USER_NAME "
          python ./cicd/simply.py
